server:
  port: 9000

spring:  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sb
    password: sb
  mvc:    pathmatch:      matching-strategy: ant-path-matcher  
  